CC = gcc

SMSH4_SRCS = smsh4.c execute2.c splitline.c process2.c controlflow.c builtin.c varlib.c
SMSH1_SRCS = smsh1-1.c execute.c splitline2.c
SMSH5_SRCS = smsh5.c execute.c splitline2.c process2.c controlflow.c builtin.c varlib.c

smsh4: $(SMSH4_SRCS)
	$(CC) -o smsh4 $(SMSH4_SRCS)

smsh1-1: $(SMSH1_SRCS)
	$(CC) -o smsh1-1 $(SMSH1_SRCS)

smsh5: $(SMSH5_SRCS)
	$(CC) -o smsh5 $(SMSH5_SRCS)

	

